subscription_id         = "903b6685-c12a-4703-ac54-7ec1ff15ca43"
resource_group_name     = "rg-platform-tf-strategic-services-permissions-uksouth"
storage_account_name    = "satfpltfrmssp3yhd"
container_name          = "tfstate"
key                     = "terraform.tfstate"